package exception;

import java.util.Scanner;

public class ExceptionHandlingExample {
    public static void main(String[] args) {

        int a[] = {2, 3, 4, 5, 6};



            try{
                for (int i = 0; i < 6; i++) {
               System.out.println(i);

            }
            }
                catch(ArithmeticException e){
                System.out.println("the given no found");

            }

            }

        }

